version: "3"

services:
  traefik:
    image: "traefik:2.0"
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - "--providers.docker=true"
      - "--api.insecure=true"
    ports:
      - "8000:80" # Ingresss port for containers.
      - "8080:8080" # The Traefik dashboard.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"
      - "traefik.http.services.${PROJECT_NAME}_portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
